### ISSUE TITLE
WM Token signature - Symmetric encryption

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#10]
For the time being, the specification only lists asymmetric crypto for the token signature. Would it be possible to also consider symmetric encryption schemes, e.g. HS256 which is already part of [rfc7515](https://datatracker.ietf.org/doc/html/rfc7515)? It implies that the header may look like {"alg":"HS256",  "kid":"2010-12-29"}.

There are two issues with asymmetric crypto token signatures
1. PKI mandates to add a longer signature to the token, which is expected to be transmitted with each client request (bandwidth overhead)
2. Asymmetric crypto is more computationally intensive (by one or two orders of magnitude. This may have impact on the density of the token generator but also on the edge latency.

**Comment by lpiron** [comment]
Agree to add symmetric crypto.

**Comment by GwenSynamedia** [comment]
Added text

"The token shall be signed as described in [5]. It shall use either HS256, RS256 or ES256 signature as described in [6] clause 3, pem key. The alg header parameter defined in [5] shall be present. How the required crypto material is shared among the actors/servers is out of the scope of this document"

Issue considered closed
