### ISSUE TITLE
WM Token - Secret/key exchange

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#11]
The specification is silent wrt. key management for the edge to be able to interpret the watermark token. Is this expected to be managed at the CDN configuration level, from some interaction with a dedicated service, other? What is the envisioned granularity of this configuration: on a customer-basis vs a. watermark vendor basis? How can these critical secret be renewed in case of leak?

**Comment by lpiron** [comment]
Is there a value for CDN provider if some requirements or one specific implementation are added in term of key management?
For a shared secret, probably nothing can be done. Most probably, per CDN provider and out of scope for this specification.

**Comment by GwenSynamedia** [comment]
Edits in the document now indicate
"How the required crypto material is shared among the actors/servers is out of the scope of this document."
There seems to be consensus to manage this at CDN distribution configuration level.

Issue considered closed
