### ISSUE TITLE
WM token - Indirect mode clarification

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#12]
It sounds like this mode delegates the generation of the actual watermark identifier used for A/B sequencing to the edge. It does have the virtue of saving sizable bandwidth when long identifiers are used e.g. to combat collusion. While the general principle is understandable, the specifics of the integration remain somewhat vague.
Does it assume that some proprietary source code (per watermark vendor) would be incorporated in the edge? This sounds to be misaligned with the general philosophy of the specification. How to renew this "WMID generation engine" when a vulnerability is identified?
Does it assume that the edge shall call another service to get a WMID? In that case, it would be helpful to indicate the sequence of calls between the two entities. How are the parameters of the "WMID generation engine" passed?
All in all, this section would benefit of some clarification.

**Comment by darth-v** [comment]
_Does it assume that some proprietary source code (per watermark vendor) would be incorporated in the edge?_ 
Each Watermarking Vendor which wants to use the indirect method would have to provide its own source code or its own algorithm to the Edge Vendor.
_How to renew this "WMID generation engine" when a vulnerability is identified?_
Options: WM token would have different version, for example, WM token would have different keyver, etc. And there would be update of what Watermarking Vendor provided to the Edge Vendor.
_Does it assume that the edge shall call another service to get a WMID?_
No, it would be IMHO counter-productive to the original intent - if another service has to be called, it's questionable if saving in bandwidth as you named it would be beneficial.
 _How are the parameters of the "WMID generation engine" passed?_
WM token says "which vendor", Edge looks-up internally for the integrated library and calls it, by passing also relevant claims (parameters) from WM token.

**Comment by lpiron** [comment]
No changes on the token format. Keep both options. 
Clarify that workflows are assuming a token in "direct mode"
Add the definition of an abstract API for the processing on the edge. API between the Edge and the Vendor specific core. One function that takes the token in the clear JWT and outputs the WMPattern.

**Comment by GwenSynamedia** [comment]
If the API is "WM token in - WM sequence out", we may want to simplify Figure 5 as it would be mostly internal stuff of the library provided by the watermark vendor if I understand correctly

**Comment by lpiron** [comment]
Text updated in the document put in review in February 2023
