### ISSUE TITLE
On-going session revocation

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#13]
DASH IF remains silent about this. At the end of the day, the objective of forensic watermarking is to blacklist some WMIDs (assigned to pirates). How would that been achieved i.e. how is the edge maintaining an up to date blacklist to be enforced? Is this beyond the scope of this document? Is it expected to be managed outside of the edge e.g. at CDN level thanks to some binding of CDNID and WMID?

**Comment by lpiron** [comment]
Most probably out of scope, but to be seen with CDN providers. Every CDN has a different approach.
Do we need a sentence explaining that this is out of scope ?

**Comment by lpiron** [comment]
Closing as the text has been updated
