### ISSUE TITLE
WM token - TTL enforcement

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#14]
Can the specification mandate that the edge shall enforce the token time to live (or the "issue at" claim in the JWT RFC)? This is critical to avoid a never-ending replay of the same token and to force the renewal of tokens in case of update/vulnerability.

**Comment by MathieuBoivin1** [comment]
Fully agree with you Gwenaël, IMO it is mandatory to add it in spec otherwise we would face issues related to this in the future. BTW, for me, it is better to use 'iat' and set a validity duration in CDN than validating 'exp' in CDN.

**Comment by lpiron** [comment]
Make sense. The claim shall be mandatory and the server processing the token shall enforce it.

**Comment by MathieuBoivin1** [comment]
What I propose in order to offer the best flexibility i.e. To be able to support validity control on both sides (WMT generator or CDN), is to set 'iat' as mandatory and 'exp' as optional. And to define that when 'exp' is present, it shall be used to check validity.

**Comment by lpiron** [comment]
Closing as the text has been updated
