### ISSUE TITLE
Modification of the WmPaceInfo payload

### ISSUE THREAD

**Issue by darth-v** [Dash-Industry-Forum/Watermarking#15]
Here is a proposal for a slight modification of the WmPaceInfo message.
The original/current one is:

```
class WMPaceInfo {
unsigned int(8) version;
unsigned int(8) variant;
unsigned int(1) emulation_1;
unsigned int(15) pos;
unsigned int(1) firstpart;
unsigned int(1) emulation_2;
unsigned int(1) iswm;
unsigned int(5) reserved;
unsigned int(8) nbpart;
}
```
The modified version would be:
```
class WMPaceInfo {
unsigned int(8) version;
unsigned int(8) variant;
unsigned int(1) emulation_1;             // <- break potential 00 00 01
unsigned int(15) pos_l15b;
unsigned int(1) emulation_2;             // <- break potential 00 00 01
unsigned int(10) pos_h10b;
unsigned int(1) firstpart;
unsigned int(1) iswm;
unsigned int(3) reserved_1;
unsigned int(1) emulation_3;              // <- break potential 00 00 01
unsigned int(10) wm_specific_data;
unsigned int(4) reserved_2;
unsigned int(1) emulation_4;              // <- break potential 00 00 01
unsigned int(8) nbpart;
}
```
The difference comes from extending "pos" (or the position attribute) from 15bits to 25bits
and adding extra 10bit for "wm_specific_data" 
Essentially "pos" is bigger than it was for 10bits and there is an extra field "wm_specific_data" of 10bits.
In total 20bits (2.5 bytes) extending payload-wise.

The other attributes/fields ("version", "variant", "firstpart", "iswm", "nbpart") are not touched.

There is only a slight shuffle in the order to try to make it least impact.
The original version is 6 bytes.
The modified version here is 9 bytes.
The difference +3 bytes (out of which 2.5 bytes used).

In theory "variant" is still 8bits, which perhaps may be seen as too optimistic considering the reality and AB Watermarking (i.e. how many different variant stream there shall exist in parallel).
So, potential savings may come from the directions of "reserved fields" and the size-of "variant"
(if going from 6 to 9 bytes is seen as too much).

Of course "emulation" bits are set to '1'.

**Comment by lpiron** [comment]
Noted with no action

**Comment by lpiron** [comment]
Closing
