### ISSUE TITLE
SEI stripping - section 5.5.4.2 

### ISSUE THREAD

**Issue by nicoweil** [Dash-Industry-Forum/Watermarking#17]
In 5.5.4.2 we shouldn’t require origins to strip out the SEI message, as it would break the HRD. Instead, we should require the origin to zero-pad the SEI.

**Comment by nicoweil** [comment]
If zero-pad is already used in the text, maybe we should just add a precision on the meaning of the expression (replacing existing bytes of the SEI with zeros).

**Comment by GwenSynamedia** [comment]
I am perfectly fine for padding instead of stripping. However, at elementary stream level, it should not be 0-padding but "neutral" padding e.g. with 0xFF (in order to avoid messing up MPEG TS parsing engines) or EPCs 0x000003. Zeros at ES layer have very strong semantics.

**Comment by lpiron** [comment]
Need to look in more details. Depends the level. elementary stream (SEI), MP4 box, TS adaptation field. Need a method for every level.

**Comment by lpiron** [comment]
Implemented in the updated version available [here](https://dashif.org/docs/IOP-Guidelines/DASH-IF-CTS-00XX-AB-Watermarking-0.9.pdf) for [review](https://dashif.org/guidelines/others/#dash-if-candidate-technical-specification-dash-if-forensic-ab-watermarking)
