### ISSUE TITLE
Watermarking at the edge ingest mode over HTTP GET

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Watermarking#18]
It seems that processing at the edge is becoming more popular, in this case a watermark could be applied post origin, i.e. after the origin. Would it make sense to include an ingest mode fot HTTP DASH/HLS with HTTP GET to enable such edge based implementations ? This could follow very similar recommendations as for the HTTP DASH/HLS/CMAF over HTTP POST, but I did not see it in the document.

**Comment by GwenSynamedia** [comment]
@RufaelDev Could you clarify your comment?
Are you referring to a delivery system
1. where the A/B duplication occurs after the JiTP/Origin
2. where watermarking is performed at the edge (no A/B duplication throughout the CDN)
3. something else.

I am aware of the existence of 1 & 2 in different flavours, but I would argue that they are beyond the scope of this spec. They usually incur additional requirements that are not required here e.g. ability to modify the binary body of the response at the edge, ability to decrypt/encrypt with the content key, etc. Such systems usually do not require additional signalling at ingest.

**Comment by lpiron** [comment]
Closed with no action
