### ISSUE TITLE
WM Token: Encryption password ID and derivation algo. Why not directly using a KID identifying an AES key?

### ISSUE THREAD

**Issue by MathieuBoivin1** [Dash-Industry-Forum/Watermarking#20]
Password, Password id 'wmidpid' and password derivation algo 'wmidpalg' sounds to me like something that is done when human is in the loop and a 'rememberable' password is needed. Here, encryption secrets are configured on both sides (WMT generator and CDN) without the need for a human to remember them - which is even preferable. What I propose is to configure AES key on both sides and to identify key with a Key ID (KID).
We could also add a stage for more security among the one proposed in JWA spec : https://datatracker.ietf.org/doc/html/rfc7518#section-4.1/.
E.g. instead of directly using the shared key to encrypt WMID, drawing a random Content Encryption Key (CEK), to wrap CEK with shared key, to transmit wrappped CEK cryptogram in JWT and to encrypt WMID with CEK (e.g. with alg:A256KW).

**Comment by lpiron** [comment]
The updated version available [here](https://dashif.org/docs/IOP-Guidelines/DASH-IF-CTS-00XX-AB-Watermarking-0.9.pdf) for [review](https://dashif.org/guidelines/others/#dash-if-candidate-technical-specification-dash-if-forensic-ab-watermarking) made this comment obsolete. We moved to a CBOR token with different claims.
