### ISSUE TITLE
WM Token: Secrets renewal support

### ISSUE THREAD

**Issue by MathieuBoivin1** [Dash-Industry-Forum/Watermarking#21]
The spec should strongly recommend or even better to make it mandatory to have 2 set of secrets (for WMT signature verification and WMID decryption) identifiable by there KID or equivalent in CDN to allow WM token secrets renewal. Secrets are identified by there KID or equivalent in WM Token and selected accordingly in CDN. This requirement allows a smooth transition from previous secrets to new secrets. During transition, both secrets sets may be selected, allowing to be flexible in term of secrets update flow.

**Comment by lpiron** [comment]
Link to comment #26

**Comment by lpiron** [comment]
Closing, addressed with #26
