### ISSUE TITLE
2.2 [i.1] Broken link to Akamai document.

### ISSUE THREAD

**Issue by MathieuBoivin1** [Dash-Industry-Forum/Watermarking#22]

**Comment by wilaw** [comment]
Can you please specify the link that is broken?

**Comment by MathieuBoivin1** [comment]
In part 2.2 Informative references, [i.1] Edge Services: Watermarking, Overview for Watermarking Partners. Version 1.9, July 2020:
https://github.com/akamai/mediadelivery/blob/master/Integration%20Specs/Akamai%20AMD%20Edge%20Watermarking%20Specification.pdf

**Comment by wilaw** [comment]
The docs have moved to https://techdocs.akamai.com/adaptive-media-delivery/docs/the-watermarking-token-wmt.

However, in speaking with Laurent, he suggested that we simply place the text of interest (as below) directly in the spec and remove the link and reference from the document. 

`ab (Default): specifies the pattern is a serouence of "A" and "B" characters. For example, wmid": "ABBABAAABBBABABBBAAABBABBAAA`

**Comment by MathieuBoivin1** [comment]
Indeed, good choice to extract usefull information and put it in spec, no risk to loose information.

**Comment by lpiron** [comment]
Closing as the text has been updated
