### ISSUE TITLE
Alternative to network calls for Wmpaceinfo transport from origin to edge

### ISSUE THREAD

**Issue by nicoweil** [Dash-Industry-Forum/Watermarking#23]
Discussed quickly on slack with Zac Shenker (Fastly) last week: "_The VOD Sidecar approach isn't really too much of an issue for us since we will fetch the Sidecar once, and then be fine after that. We are much more concerned with the Live approach and the impact of multiple requests for every segment._"

We have a couple of problems with the "one preliminary HTTP call per segment" approach:
- it generates a lot of additional HTTP requests, and further more with LL-HLS where parts are usually 1s long
- it's supposed to be a way to avoid unecessary fetches of A or B variants, but in practice we know that watermarking will be applied on popular contents, meaning that anyways A and B variants will be fetched from the origin by the CDN
- it still requires one extra HTTP wmpaceinfo call and and one edge function execution per segment even if watermarking is disabled (and this comes with a cost)

So I'm suggesting the following alternative:
- the origin adds the binarized/lightweight Wmpaceinfo metadata as a HTTP response header to all segments responses (per segment wmpaceinfo for discrete segments or full content wmpaceinfo for byteranges, if max header size is compatible)
- the CDN systematically fetches both A and B versions of the segments, gets the Wmpaceinfo from the HTTP header of these segments/ranges, analyzes the Wmpaceinfo data and picks which A or B variant to return

It can work fine with a neutral manifest, with the A segments being located on a neutral path (no /a/ sub-path) and the B segments being located on a /b/ sub-path. Constraint: the location of B segments needs to be defined in the CDN configuration.

The current logic for signaling watermarking as disabled doesn't work well as you still need to download the Wmpaceinfo from the metadata endpoint to understand if the switching logic must be executed fully. So there is no way with this approach to avoid any 
edge function execution, even minimalistic. I suggest to move the signaling of watermarking being enabled or disabled to the CDN configuration level, which will be more optimized, as you can explicitely define contents paths where watermarking needs to be applied, instead of relying on one network call per segment just to find out that watermarking must not be applied.

**Comment by RobertLabonte** [comment]
We agree with this proposal, but have concerns about origins being able to properly support this. The data size of WMPaceInfo for VOD byte ranges may be too large to pass as a header. While investigating potential [binary sidecar formats](https://github.com/Dash-Industry-Forum/Watermarking/issues/1), the smallest we were able to shrink a 1800 entry WMPaceInfo sidecar was to 44kB. A more minimal WMPaceInfo data layout will reduce the data size, but likely not enough to remove the concern for longer duration content.  

In light of concerns about origin support and data size, we support the header approach as an additional option in conjunction with mandatory support sidecar files.

**Comment by nicoweil** [comment]
Sidecar files work well for on-demand profile VOD contents, as we have no header max size problem in this case, and it aligns well with the logic of having a single track file per representation. That would make sense to keep the sidecar file approach for this specific use case, indeed.

In order for both approaches to co-exist cleanly, I think there should be a CDN configuration parameter to define the source of the Wmpaceinfo (sidecar file on a discrete HTTP endpoint, or HTTP header). That would avoid to fallback from one approach to the other after an initial error.

As regards the "_CDN systematically fetches both A and B versions of the segments_" CDN behavior, it's just one possible option, the other being "_CDN fetches A version of the segment, extract and analyzes the header, and eventually requests B version if the bit position is not in line with the token_". It's an internal  implementation detail that should be left to the CDN to decide.

**Comment by GwenSynamedia** [comment]
One proposal up for discussion was to keep the requirement of having the wmpaceinfo endpoint at origin but also to incorporate the WMPaceInfo atom in the header of the response to segment requests. This will leave some flexibility to the CDN on how to implement the A/B logic: pulling wmpaceinfo first vs. requesting both A/B Variants at once.

One implementation vs. the other may be dependent on the popularity of the content / size of the deployment.

Note that requesting both Variants at once does require to know the prefix needed to reach the Origin A&B endpoints. As mentioned by Nicolas, this may be managed at CDN configuration level since I do not anticipate that a given service provider will use different A/B prefixes for alternate assets/channels. If we do decide to move this definitions at CDN configuration level, we may want to be explicit about it in the document (and list other parameters that may be there). I will create another dedicated issue for this.

**EDIT:** If the WMPaceInfo content is placed in the header of the response between Packager and Edge, it shall be stripped prior to being forwarded to the client

**Comment by lpiron** [comment]
Text added to the document. Bug to be closed by mid-august if no comments

**Comment by lpiron** [comment]
Implemented in the updated version available [here](https://dashif.org/docs/IOP-Guidelines/DASH-IF-CTS-00XX-AB-Watermarking-0.9.pdf) for [review](https://dashif.org/guidelines/others/#dash-if-candidate-technical-specification-dash-if-forensic-ab-watermarking)
