### ISSUE TITLE
sidecar file content

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/Watermarking#24]
Extracted from issue #1 for tracking as this is not related to the binary format discussion
Proposed Sidecar Changes:
- Limit data in sidecar to only data required by CDNs (startRange, endRange, pos)
- Remove one level of indirection, segments should be a single dictionary object to improve JSON parsing speed.
- Remove non-watermarked segments from the segments dictionary list. It's unlikely watermarked and non-watermarked will be interspersed, so make a high level field identifying at what byte position watermarking begins. All requests before the first watermarking byte position will be honored by a CDN. This would also allow for the removal of the "iswm" bool in segments list.
-  Make "version" a top level key/value, to prevent redundant reading of the same data in each segment.

Example WM sidecar JSON with proposed changes:

      "version": 1,
      "segmentType": "byterange",
      "iswmStartRange": 22510,
      "variantSubPaths": [
         {
           "variant": 0,
           "subPath": "a"
         },
         {
           "variant": 1,
           "subPath": "b"
         }
      ],
     "segments": [
         {
           "startRange": 22510,
           "endRange": 524067,
           "pos": 0
         },
        {
           "startRange": 524068,
          "endRange": 1024868,
          "pos": 1
        }
     ]
     }

**Comment by lpiron** [comment]
This has been discussed during the F2F. There is a general agreement that it makes sense. The content of the sidecar file will be modified accordingly.

**Comment by GwenSynamedia** [comment]
Open discussion points about the sidecar format
- do we really need to specify the iswmStartRange since it is equal to the first startRange in the segments list?
- do we really need to specify the endrange for each segment since, with the current working assumption (no audio interleaving), the video mdat is contiguous and the endrange of a segment is equal to startrange-1 of the previous segment.

I would also suggest considering discarding variantSubPaths if we do decide to declare these at CDN configuration level (cf. #23 ). In essence, it boils down to make the egress sidecar file only contain content-specific data.

Note, that we may need to keep the variantSubPaths for the ingest sidecar file so that the Packager knows where to fetch the A&B Variants in input.

**Comment by RobertLabonte** [comment]
>>do we really need to specify the iswmStartRange since it is equal to the first startRange in the segments list?

Making `iswmStartRange` a top level key/value allows for delivering the two separate requests for MOOV and SIDX atoms without having to parse the `segments` array into memory. Top-level key/values are inexpensive both in terms of compute and data size, but parsing the `segments` array can be computationally expensive. 

>>do we really need to specify the endrange for each segment since, with the current working assumption (no audio interleaving), the video mdat is contiguous and the endrange of a segment is equal to startrange-1 of the previous segment.

There is a lot going on in [Issue #1](https://github.com/Dash-Industry-Forum/Watermarking/issues/1), but the case against only having `startRange` was addressed there:

>>Removing "endRange" in sidecar segments will make delivering the last segment difficult. It can also lead to relying on backend server behavior and the possibility to "fail open" if a segments list is truncated somehow in a sidecar. 

However, these issues can easily be overcome by adding top-level key/value `iswmEndRange` to be used when the last element in the `segments` array is encountered.  

Example WM sidecar layout in JSON format:
```
{
  "version": 1,
  "segmentType": "byterange",
  "iswmStartRange": 22510,
  "iswmEndRange": 1024868,
  "variantSubPaths": [
    {
      "variant": 0,
      "subPath": "a"
    },
    {
      "variant": 1,
      "subPath": "b"
    }
  ],
  "segments": [
    {
      "startRange": 22510,
      "pos": 0
    },
    {
      "startRange": 524068,
      "pos": 1
    }
  ]
}
 ```

**Comment by GwenSynamedia** [comment]
Point taken about endRange needed for last segment.
But in that case, I would go for the dual proposal: no startRange in segments but endRange instead.
This is assuming that there are no trailing bytes after endRange.

```
{
  "version": 1,
  "segmentType": "byterange",
  "iswmStartRange": 22510,
  "variantSubPaths": [
    {
      "variant": 0,
      "subPath": "a"
    },
    {
      "variant": 1,
      "subPath": "b"
    }
  ],
  "segments": [
    {
      "endRange": 524067,
      "pos": 0
    },
    {
      "endRange": 1024868,
      "pos": 1
    }
  ]
}
```

Note that if we decide to go for #26 (endpoint declaration at CDN configuration level), the variantSubPaths section will not be present in the **egress** sidecar file reaching the edge.

```
{
  "version": 1,
  "segmentType": "byterange",
  "iswmStartRange": 22510,
  "segments": [
    {
      "endRange": 524067,
      "pos": 0
    },
    {
      "endRange": 1024868,
      "pos": 1
    }
  ]
}
```

I do see the data compaction virtue of the proposal. However, I am not a CDN provider and will not be the one consuming this data. Any objection wrt. CDN efficiency and/or explicit vs. implicit signalling?

**Comment by lpiron** [comment]
remove subPath, become part of the edge-origin configuration
Need to be reviewed taking into account CBOR for efficiency. The "range" key is the most important for getting data from this file and keep both start and end values.

  "version": 1,
  "segmentType": "byterange", -> can become an integer (0=byterange, 1=discrete)
  "iswmStartRange": 22510,
  "segments": [
     {
       "range": 22510-524067, (can be an array)
       "pos": 0
     },
    {
       "range": 524068-1024868,
      "pos": 1
    }
 ]

**Comment by msanmart-akamai** [comment]
A more compact format including all previous suggestions. The subPath and range are interpreted as positional arrays with two values:  range=[start, end] and variantSubPath[vatiant_0,variant_1].

<pre><code>
{
   "version" : 1,
   "segmentType" : 0,
   "variantSubPaths" : ["A", "B"], // subpath names may be a packager decision so one configuration for all assets may not be a good choice?
   "segments": [
      {
          "range":[0, 34506],
          "pos":0
      },
      {
          "range":[34507, 73179],
          "pos":1
      },
      {
          "range":[73180, 111858],
          "pos":2
      },
      {
          "range":[111859, 181432],
          "pos":3
      },
      {
           "range":[181433, 248785],
           "pos":4
      },

      ...

      {
           "range":[298721433, 29889535],
           "pos":1332
      }
    ]
}
</pre></code>

**Comment by lpiron** [comment]
Implemented in the updated version available [here](https://dashif.org/docs/IOP-Guidelines/DASH-IF-CTS-00XX-AB-Watermarking-0.9.pdf) for [review](https://dashif.org/guidelines/others/#dash-if-candidate-technical-specification-dash-if-forensic-ab-watermarking)
