### ISSUE TITLE
VOD segment flavor - Monolithic sidecar file at the edge

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#25]
There has been a bit of discussion during the 2022 F2F meeting in Berlin.

The current mindset of the document is that a monolithic sidecar file would be provided at ingest, both for byte-range and segment format. However, the expected behavior of the Packager/Origin differs depending on the format:

1. For byte-range format, the monolithic sidecar file is forwarded to the edge so that byterange enforcement can be applied
2. For segment format, the Packager is expected to extract the WMPaceInfo "atom" associated to the segment and only forward this to the edge.

This difference of behavior originates from the history of the specification write up (live > VOD segment > VOD byte range). Nevertheless, some CDN providers have expressed that this may be inefficient and that it would also be preferable to have a monolithic WMPaceInfo for the VOD segment flavor.

**Pros:** save the need to request WMPaceInfo for each segment (HTTP traffic), simplify the Packager logic
**Cons:** parsing of the monolithic WMPaceInfo file for each segment request

The issue is to collect additional feedback whether we do want the feature "monolithic sidecar in VOD segment". Note that it may raise challenges wrt to cache key since we were previously using the wmpaceinfo/segment_filename as the cache key for the WMPaceInfo atom.

**Comment by lpiron** [comment]
To be closed without action following discussion on #23

**Comment by lpiron** [comment]
Closing
