### ISSUE TITLE
Explicit CDN configuration description

### ISSUE THREAD

**Issue by GwenSynamedia** [Dash-Industry-Forum/Watermarking#26]
We have several places where we suggest that things may be managed at CDN configuration level. Should we consolidate these working assumptions in a dedicated paragraph that enumerates CDN configuration parameters relevant for this specification.

- #11 suggests that the configuration of the crypto secrets will be managed at CDN configuration level
- #23 and #24 hint that it may be more optimal to have the A/B upstream prefixes configured at CDN level
- #23 may lead to two alternate implementations of the edge logic and there may be a dedicated parameter if a CDN vendor decides to implement both.
- Another CDN configuration parameter may be where to look for the WM token: URI, query parameter, header

**Comment by wilaw** [comment]
Another required CDN action would be to strip any header-based WMPaceInfo before returning a segment to a client. This is not so much a config option as it is a required CDN behavior, but it might be worth adding it to a new 'CDNs must do this' section.

**Comment by lpiron** [comment]
Add the Variant path to the configuration

**Comment by lpiron** [comment]
Implemented in the updated version available [here](https://dashif.org/docs/IOP-Guidelines/DASH-IF-CTS-00XX-AB-Watermarking-0.9.pdf) for [review](https://dashif.org/guidelines/others/#dash-if-candidate-technical-specification-dash-if-forensic-ab-watermarking)
