### ISSUE TITLE
Watermarking and Content Steering

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Watermarking#28]
As multiple variants are used and the location of the variants may be different, there should be a careful check to what extent the specification of Watermarking and [Content Steering](https://dashif.org/news/content-steering-2/) may contradict.

**Comment by nicoweil** [comment]
The location of the variants is indeed different on the origin, but from a player perspective - and in terms of CDN entries for Content Steering - this is totally identical to a scenario where no A/B watermarking is used. The only difference is that the CDN needs to fetch the segments from the origin conditionally (segment variant A or B depending on the end user unique signature and the watermarking bit position of the requested segment). So we should be good here.

**Comment by lpiron** [comment]
Closing with no action
