### ISSUE TITLE
Ads insertion and content stitching

### ISSUE THREAD

**Issue by yongjuw** [Dash-Industry-Forum/Watermarking#3]
Recommend to discuss ads insertion and content stitching in more details in live streaming and video on demand separately, currently as part of section 5.3.5. The existing discussions and statements in section 5.3.5 focus on live streaming only and should cover video on demand too. 

*Section 5.3.5.1 Ads insertion and content stitching in live streaming* 

In live streaming, ads (secondary contents) could be inserted without ad break (SCTE signaling for example) markers, as burn-in ads (secondary contents). In such scenarios, the encoder will have no knowledge about whether the coming contents are ads (secondary contents) and should not have watermarking applied, and it should continue apply watermarking as usual. 

When ads (secondary contents) are inserted with ad break markers, the break may happen at any time. As every segment carries watermarking information allowing to perform the detection, there shall not be segments carrying conflicting data. While some techniques may recover from this mix of data, it will, in all cases, impact the length of content needed for retrieving the WMID. 

......

Some devices may receive the original content if no ad can be found for replacement. One consequence is that these devices receive content that is meant to be watermarked following the rules of this document. The encoder shall apply no watermarking on all segment part of the ad break. In this case, the encoder shall forward to the packager WMPaceInfo that contains iswm equal to false. 

*Section 5.3.5.2 Ads insertion and and content stitching in video on demand*

In video on demand, ads (secondary contents) will be inserted or stitched with ad break (cue in/out points for example) markers. The device should consume ads (secondary contents) from an alternative edge for the full duration of the ad break. The alternative edge server should not enforce watermarking and gracefully ignore the WM token. 

If some parts of main content are replaced and stitched with alternative replacements of main content, 

* the encoder should apply no watermarking on all the segment parts of the replacement duration if the total duration of replacements is not significant, which might impact the length of content needed for retrieving the WMID, 
* or the encoder should apply watermarking on all the segment parts of the replacement duration. In this case, the encoder shall prepare A and B Variants for main content in the replacement duration, and all the alternative replacements together with their WMPaceInfo.

**Comment by lpiron** [comment]
The section will be edited as, in case of Live, original ads will be watermarked. Some elements could be added for clarification.

**Comment by lpiron** [comment]
Closing as the text has been updated
