### ISSUE TITLE
Watermarking Pattern bit/byte order undefined

### ISSUE THREAD

**Issue by darth-v** [Dash-Industry-Forum/Watermarking#32]
Traditionally wmpattern order was defined by a WM Vendor.
Consequently, some differences were visible in the past among different vendors, and then a prior integration would limit a later integration (one vendor being integrated prior to the other vendor, would produce issues for the other vendor).
Initially, in 2021, this topic was briefly discussed in WM IOP meetings, but it got lost from our radar afterwards.

So, options I see for this are:
- separate interpretations for direct and indirect cases, where direct would assume least significant leftmost, while indirect case would assume the opposite with least significant rightmost
- joined interpretations but inclusion of the extra CWT claim "wmpat_byte_order" which would define "0 == least significant leftmost", "1 == least significant rightmost"

For example, for Irdeto this is default:
0x60be9d382e3241ae15f8824d51d18540262beaa150b52902ac37bf5a5bf8f39147cf059f05609c89fcbb8a1d98aa8d8c0318d6c8d4cb967667fbac0633a2ce74
where:
o	LSB is 0x74
o	MSB is 0x60

I dare to assume that for some other vendor(s) the following might be default:
0x2e7345cc6035dfe66e69d32b136b18c031b15519b851dd3f913906a0f9a0f3e289cf1fda5afdec354094ad0a8557d46402a18b8ab2411fa875824c741cb97d06
where:
o	LSB is 0x06
o	MSB is 0x2e

Both values correspond to the same, but due to different interpretation of the order, they becomes very different.

**Comment by lpiron** [comment]
Closed as all parties agree.
