### ISSUE TITLE
The links in the document https://dashif.org/docs/DASH-IF-IOP_OTT-Watermarking.pdf are not found

### ISSUE THREAD

**Issue by harishinka** [Dash-Industry-Forum/Watermarking#34]
One of the link mentioned under section 2.2
[i.1]Edge Services: Watermarking, Overview for Watermarking Partners. Version 1.9, July 2020. URL:
https://github.com/akamai/mediadelivery/blob/master/Integration%20Specs/Akamai%20AMD%20Edge%20Watermarking%20Specification.pdf 
results in Error 404. Either the link can be corrected or removed.

**Comment by lpiron** [comment]
https://dashif.org/docs/DASH-IF-IOP_OTT-Watermarking.pdf is a preliminary version of the document. We corrected and updated quite a lot. Please have a look at the released version is at  https://dashif.org/guidelines/others/ where this has been corrected.

**Comment by harishinka** [comment]
Thank you so much @lpiron for your prompt response. I will bookmark the new URL for future reference.
