### ISSUE TITLE
DASH-IF specification on handling Catchup use case

### ISSUE THREAD

**Issue by harishinka** [Dash-Industry-Forum/Watermarking#35]
Will the DASH-IF have a specific use case for handling Catchup use case of Live event, where the user can switch from Live mode to the past events on the same stream and re-join the live streaming

**Comment by lpiron** [comment]
There is no plan to add a section on this use case. The pace of the watermark ID is broken with the case you describe but the right Variant is delivered for every segment. It could then be the responsibility of the watermark vendor to check whether or not it can recover any ID from this stream. Now, such stream (if added in a pirate site) does not have a real value. One would need to edit it to remove the back and forth from catch-up and the watermark ID is then properly recreated.

**Comment by harishinka** [comment]
Thank you so much for the clarification @lpiron
