### ISSUE TITLE
HLS MPEG-2 TS

### ISSUE THREAD

**Issue by yongjuw** [Dash-Industry-Forum/Watermarking#4]
In section 5.3.5, it should add “This solution does not allow creating aligned segment when content is delivered with HLS in the form of MPEG-2 TS segments encrypted with AES sample encryption, due to the fact that start code emulation prevention must be re-applied over the entire NAL unit after Apple HLS encryption with MPEG-2 TS. ” and “An alternative solution available is to 1) not use segments requested as byte ranges, but to use discrete files. In this case, there is no need to align Variant A and B of the same segment, 2) or use CMAF segments with HLS where start code emulation prevention is not re-applied after encryption.”

**Comment by lpiron** [comment]
Agreed. The text will be clarified accordingly.

**Comment by lpiron** [comment]
Closing as the text has been updated
