### ISSUE TITLE
Alternative options to turn off watermarking

### ISSUE THREAD

**Issue by yongjuw** [Dash-Industry-Forum/Watermarking#5]
In section 5.5.5, it should add some alternative option that “alternatively, it can completely deprecate forensic watermarking Variants and use a separate URL pointing to a different video asset re-encoded and packaged with forensic watermarking disabled, and no computation, storage and caching overhead in the delivery chain”.

**Comment by lpiron** [comment]
The spec does not prevent doing this way but this is more a content management issue rather than a CDN edge management issue.

**Comment by lpiron** [comment]
Closing with no update
