### ISSUE TITLE
WMPaceInfo

### ISSUE THREAD

**Issue by yongjuw** [Dash-Industry-Forum/Watermarking#6]
In section 5.3.3.1, it should add that “When WMPaceInfo is delivered in TS adaptation field, ISOBMFF file format, or SEI, it will add some overhead in the last mile delivery from CDN, ISP to players on devices. Instead, the option of sidecar or HTTP header do not add overheads in the last mile. One option for conveying WMPaceInfo information should be sufficient, not necessary to use multiple options at the same time. Options in Table 2 are for the delivery of WMPaceInfo from encoder to origin. Origin should zero reset SEIs, TS adaptation field or ISOBMFF box. Origin should deliver WMPaceInfo through HTTP headers to CDN, and CDN caches WMPaceInfo in a separate file(s).”

“... in order to facilitate content manipulation when zero-padding it.” should be “... in order to facilitate content manipulation when zero-resetting it.”

**Comment by lpiron** [comment]
Add a note stating that two methods should not be instantiated at the same time?
The second comment (on zero-padding) is handled with #17

**Comment by lpiron** [comment]
Closing as the text has been updated
