### ISSUE TITLE
video download

### ISSUE THREAD

**Issue by yongjuw** [Dash-Industry-Forum/Watermarking#7]
Video download for offline video playback is often available on mobile devices, such as iPhone, iPad, Android phone and tablets, and web browsers by OTT providers, such as Prime Video and Netflix. When video download is supported without DASH or HLS manifests, forensic watermarking can’t be enabled by using Variants in the delivery chain and should be out of scope of DASH-IF IOP Watermarking specification. When video download is supported through DASH or HLS manifest and segments, but only uses one bit rate without ABR switching, forensic watermarking can still be enabled by using Variants in the delivery chain, and should be in the scope of DASH-IF IOP Watermarking specification with some extensions and additional requirements. 

Usually the player requests a big byte range, containing multiple video segments from one bit rate in DASH or HLS manifest, in video download scenario. The additional requirements are that 

* Since one byte range request per segment has the overhead of HTTP round trip and latency, in video download scenario a typical optimization is to request a big byte range containing multiple segments, rather than one byte range per segment as video download comes from the same single bit rate without ABR switching. Each byte range request in video download scenario shall contain one or multiple full segments, without any partial segments. It requires an evolution of clause 5.5.4.3 to say that wider byte ranges matching exactly the boundaries of concatenated segments ranges defined in the WMpaceinfo sidecar file are valid, and must be accepted by the CDN.
* CDN edge servers shall map one big byte range to small byte ranges of different full segments, and retrieve individual segments from Variant A or B accordingly using WMPaceInfo and WM Token, same as video streaming with ABR switching, and aggregate a specific sequence of A and B segments per end user, based on the unique sequence defined in the token and the WMpaceinfo sidecar file.

**Comment by lpiron** [comment]
For download use case
- Use the announced byteranges (MPD, HLS media playlist or sidx). Splitting a single request in multiples requests from the edge to the origin is not possible, especially when the mix of all segments is unique per device, hence cannot be cached.
- Use a proxy ensuring that the edge gets requests that are aligned on allowed byteranges.

**Comment by lpiron** [comment]
Closing as the text has been updated
