### ISSUE TITLE
Pausing watermarking during ad breaks

### ISSUE THREAD

**Issue by nicoweil** [Dash-Industry-Forum/Watermarking#8]
This is generating a lot of complexity on the encoder side. Unless there is a proven business need for that, AWS Elemental recommends to remove this requirement from the spec.

**Detailed explanation**:
This is seen as highly complex by the team (especially the no watermark requirement on the last segment before the ad break, as this is a downstream segmentation-level consideration influencing an upstream encoding-level decision), they don’t like it, at all. They would like to understand in details why the encoder needs to do that, given the fact that SSAI anyways creates holes in the A/B sequences, and that detection mechanisms anyways need to restart signatures acquisition after the ad breaks. One of the reason they don’t like this mechanism is that if the encoding session starts during an ad break, they have no way of not watermarking the stream at this time.  The other concern/question is to know which component is responsible for restarting the position counter after the ad break, and from which value. This cadence resetting is at best under-specified.

**Comment by lpiron** [comment]
Agree. The text will be updated accordingly. Remove the requirement.

**Comment by lpiron** [comment]
Closing as the text has been updated
