### ISSUE TITLE
Byteranges of the Multitrack MP4 files

### ISSUE THREAD

**Issue by darth-v** [Dash-Industry-Forum/Watermarking#9]
The topic has been discussed on 11-05-2022. 
The issue comes from the fact that audio sidx and video sidx will show overlapping byte-ranges, showing "iswm:false" for audio and "iswm:true" for video, leading to wrong conclusions in Edge.
And it was stated that muxed/multitrack files are out of the scope on 11-05-2022.
I am logging this per request of the chairman, so that the document depicts in writing that multitrack/muxed byteranges are out of the scope.

**Comment by lpiron** [comment]
Closing as the text has been updated
